
# SEO settings
title: "Dream"
title2: "Big" # default: ""
description: "Here's to Dream Big"
#keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: http://liyouvane.github.io # site url
#baseurl: "/thinkspace" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/liyouvane/liyouvane.github.io
disqus_shortname: "liyouvane"
twitter_username: "liyouvane"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Valerie Li"
  job      : "Student at New York University"
  bio      : "Perstare et praestare."
  thumb    : /images/author.jpg
  email    : liyouvane@gmail.com
  url      : http://liyouvane.github.io
  github   : http://github.com/liyouvane
  twitter  : http://twitter.com/liyouvane
  facebook : https://www.facebook.com/liyouvane
  linkedin : http://linkedin.com/in/liyouvane

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@liyouvane"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : home
    title: Home
  - slug : about
    title: About
  - slug : resume
    title: resume
    
exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
